#!/bin/sh

TARGET_IP="192.168.137.2"
TARGET_NETMASK="255.255.255.0"
TARGET_GATEWAY="192.168.137.1"
TARGET_NAMESERVER="1.1.1.1"

MAX_RETRIES=10
retries=0

usb0_config()
{
current_ip=`ifconfig usb0 | grep -o 'inet addr:[^ ]*' | awk -F ':' '{print $2}'`

echo "current_ip = $current_ip"

echo "TARGET_IP = $TARGET_IP"

while [[ "$current_ip" != "$TARGET_IP" && $retries -lt $MAX_RETRIES ]]; do
        sleep .5

        echo "luckfox : set usb0 ip"
        ifconfig usb0 "$TARGET_IP" netmask "$TARGET_NETMASK" 

        current_ip=`ifconfig usb0 | grep -o 'inet addr:[^ ]*' | awk -F ':' '{print $2}'`
        echo $current_ip

        retries=$((retries + 1))
done

if [[ "$current_ip" != "$TARGET_IP" ]]; then
        echo "usb0 config error"
else
        echo "usb0 config success"
        route add default gw "192.168.137.1"
        echo "nameserver $TARGET_NAMESERVER" > /etc/resolve.conf
fi
}

case $1 in
        start)
                usb0_config
                ;;
        stop)

                ;;
        *)
                exit 1
                ;;
esac

